#!/bin/sh
ar x skypeforlinux-64-alpha.deb 
rm -f skypeforlinux-64-alpha.deb 
tar xf data.tar.xz
rm -f control.tar.gz data.tar.xz debian-binary
mv usr/* .
rmdir usr
mkdir -p export/share/applications
sed -e 's/Icon=skypeforlinux/Icon=com.skype.Client/' -e 's/\/usr\/bin\/skypeforlinux/\/app\/bin\/skype/' share/applications/skypeforlinux.desktop > export/share/applications/com.skype.Client.desktop
echo StartupWMClass=Skype >> export/share/applications/com.skype.Client.desktop
mkdir -p export/share/icons/hicolor/256x256/apps
cp share/icons/hicolor/256x256/apps/skypeforlinux.png export/share/icons/hicolor/256x256/apps/com.skype.Client.png
